// export interface Language {
//   code: string;
//   name: string;
// }

// export const languages: Language[] = [
//   {code: 'en', name: 'English'},
//   {code: 'es', name: 'Spanish'},
//   {code: 'fr', name: 'French'},
//   {code: 'de', name: 'German'},
//   {code: 'zh', name: 'Chinese (Mandarin)'},
//   {code: 'ja', name: 'Japanese'},
//   {code: 'ru', name: 'Russian'},
//   {code: 'ar', name: 'Arabic'},
//   {code: 'pt', name: 'Portuguese'},
//   {code: 'hi', name: 'Hindi'},
//   {code: 'it', name: 'Italian'},
//   {code: 'nl', name: 'Dutch'},
//   {code: 'ko', name: 'Korean'},
//   {code: 'sv', name: 'Swedish'},
//   {code: 'tr', name: 'Turkish'},
//   {code: 'el', name: 'Greek'},
//   {code: 'cs', name: 'Czech'},
//   {code: 'fi', name: 'Finnish'},
//   {code: 'bn', name: 'Bengali'},
//   {code: 'pl', name: 'Polish'},
//   {code: 'th', name: 'Thai'},
//   {code: 'vi', name: 'Vietnamese'},
//   {code: 'id', name: 'Indonesian'},
//   {code: 'ms', name: 'Malay'},
//   {code: 'da', name: 'Danish'},
//   {code: 'no', name: 'Norwegian'},
//   {code: 'uk', name: 'Ukrainian'},
//   {code: 'hu', name: 'Hungarian'},
//   {code: 'ro', name: 'Romanian'},
//   {code: 'sk', name: 'Slovak'},
//   {code: 'bg', name: 'Bulgarian'},
//   {code: 'hr', name: 'Croatian'},
//   {code: 'sr', name: 'Serbian'},
//   {code: 'sl', name: 'Slovenian'},
//   {code: 'lt', name: 'Lithuanian'},
//   {code: 'lv', name: 'Latvian'},
//   {code: 'et', name: 'Estonian'},
//   {code: 'fa', name: 'Persian'},
//   {code: 'sw', name: 'Swahili'},
//   {code: 'ta', name: 'Tamil'},
//   {code: 'te', name: 'Telugu'},
//   {code: 'ml', name: 'Malayalam'},
//   {code: 'kn', name: 'Kannada'},
//   {code: 'ur', name: 'Urdu'},
//   {code: 'pa', name: 'Punjabi'},
//   {code: 'gu', name: 'Gujarati'},
//   {code: 'mr', name: 'Marathi'},
//   {code: 'am', name: 'Amharic'},
//   {code: 'so', name: 'Somali'},
//   {code: 'my', name: 'Burmese'},
//   {code: 'kk', name: 'Kazakh'},
//   {code: 'mn', name: 'Mongolian'},
//   {code: 'ka', name: 'Georgian'},
//   {code: 'hy', name: 'Armenian'},
//   {code: 'ca', name: 'Catalan'},
//   {code: 'is', name: 'Icelandic'},
//   {code: 'multiple', name: 'Multilingual'},
// ];
